# Generated by Django 6.0.5 on 2026-05-07 00:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('is_authorized', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(blank=True, max_length=150)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('category', models.CharField(choices=[('HERRAMIENTA_ELECTRICA', 'Herramienta eléctrica'), ('HERRAMIENTA_MECANICA', 'Herramienta mecánica'), ('MOTOR_ELECTRICO', 'Motor eléctrico'), ('MOTOR_COMBUSTION', 'Motor a combustión')], max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('default_revision_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('default_labor_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipment', to='equipment.brand')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
