# Generated by Django 6.0.5 on 2026-05-10 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_remove_equipment_serial_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='product_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='category',
            field=models.CharField(choices=[('HERRAMIENTA_ELECTRICA_CABLE', 'Herramienta eléctrica con cable'), ('HERRAMIENTA_ELECTRICA_INALAMBRIC', 'Herramienta eléctrica inalámbrica'), ('HERRAMIENTA_NEUMATICA', 'Herramienta neumática'), ('HERRAMIENTA_HIDRAULICA', 'Herramienta hidráulica'), ('MOTOR_ELECTRICO', 'Motor eléctrico'), ('MOTOR_GASOLINA', 'Motor a gasolina'), ('MOTOR_DIESEL', 'Motor diésel'), ('PLANTA_ELECTRICA_GASOLINA', 'Planta eléctrica a gasolina'), ('PLANTA_ELECTRICA_DIESEL', 'Planta eléctrica diésel'), ('SOLDADOR_INVERSOR', 'Soldador inversor'), ('SOLDADOR_CONVENCIONAL', 'Soldador convencional'), ('MOTOSOLDADOR', 'Motosoldador'), ('CORTADOR_PLASMA', 'Cortador de plasma'), ('OXICORTE', 'Equipo de oxicorte'), ('AGROFORESTAL', 'Agroforestal (motosierra, guadaña, podadora)'), ('LINEA_BLANCA', 'Línea blanca (electrodomésticos)')], max_length=40),
        ),
    ]
