# Generated by Django 6.0.5 on 2026-05-15 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_equipment_product_type_alter_equipment_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='brand_labor_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
