# Generated by Django 6.0.5 on 2026-05-07 00:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('equipment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ot_number', models.PositiveIntegerField(editable=False, unique=True)),
                ('service_type', models.CharField(choices=[('COBRO', 'Al cobro'), ('GARANTIA', 'Garantía')], max_length=10)),
                ('status', models.CharField(choices=[('RECIBIDO', 'Recibido'), ('INGRESADO', 'Ingresado'), ('EN_REVISION', 'En revisión'), ('REVISADO', 'Revisado'), ('EN_ESPERA_MARCA', 'En espera de respuesta de marca'), ('NEGACION_GARANTIA', 'Negación de garantía'), ('COTIZADO', 'Cotizado'), ('EN_ESPERA_REPUESTOS', 'En espera de repuestos'), ('REPUESTOS_EN_TALLER', 'Repuestos en taller'), ('EN_REPARACION', 'En reparación'), ('LISTO_PARA_ENTREGAR', 'Listo para entregar'), ('ENTREGADO', 'Entregado')], default='RECIBIDO', max_length=25)),
                ('brand_ot_number', models.CharField(blank=True, max_length=100)),
                ('problem_description', models.TextField()),
                ('received_condition', models.TextField()),
                ('revision_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('labor_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('final_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='clients.client')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='created_orders', to=settings.AUTH_USER_MODEL)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='equipment.equipment')),
                ('repair_technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='repair_orders', to=settings.AUTH_USER_MODEL)),
                ('reviewing_technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reviewing_orders', to=settings.AUTH_USER_MODEL)),
                ('warranty_brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='warranty_orders', to='equipment.brand')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(blank=True, max_length=25)),
                ('to_status', models.CharField(max_length=25)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='orders.workorder')),
            ],
            options={
                'ordering': ['changed_at'],
            },
        ),
    ]
