# Generated by Django 6.0.5 on 2026-05-08 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
