# Generated by Django 6.0.5 on 2026-05-09 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_workorder_serial_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='ot_number',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
