# Generated by Django 6.0.5 on 2026-05-09 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_workorder_ot_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='status',
            field=models.CharField(choices=[('INGRESADO', 'Ingresado'), ('EN_REVISION', 'En revisión'), ('REVISADO', 'Revisado'), ('EN_ESPERA_MARCA', 'En espera de respuesta de marca'), ('NEGACION_GARANTIA', 'Negación de garantía'), ('COTIZADO', 'Cotizado'), ('EN_ESPERA_REPUESTOS', 'En espera de repuestos'), ('REPUESTOS_EN_TALLER', 'Repuestos en taller'), ('EN_REPARACION', 'En reparación'), ('LISTO_PARA_ENTREGAR', 'Listo para entregar'), ('ENTREGADO', 'Entregado')], default='INGRESADO', max_length=25),
        ),
    ]
