# Generated by Django 6.0.5 on 2026-05-12 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_workorder_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='workorder',
            name='revision_paid',
            field=models.BooleanField(default=False),
        ),
    ]
