# Generated by Django 6.0.5 on 2026-05-13 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_spare_part'),
    ]

    operations = [
        migrations.AddField(
            model_name='sparepart',
            name='available_in_shop',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='sparepart',
            name='unit_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
