# Generated by Django 6.0.5 on 2026-05-14 01:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_spare_part_available_nullable_price'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workorder',
            name='final_price',
        ),
        migrations.AlterField(
            model_name='workorder',
            name='status',
            field=models.CharField(choices=[('INGRESADO', 'Ingresado'), ('EN_REVISION', 'En revisión'), ('REVISADO', 'Revisado'), ('EN_ESPERA_MARCA', 'En espera de respuesta de marca'), ('NEGACION_GARANTIA', 'Negación de garantía'), ('COTIZADO', 'Cotizado'), ('EN_ESPERA_ABONO', 'En espera de abono'), ('EN_ESPERA_REPUESTOS', 'En espera de repuestos'), ('REPUESTOS_EN_TALLER', 'Repuestos en taller'), ('EN_REPARACION', 'En reparación'), ('LISTO_PARA_ENTREGAR', 'Listo para entregar'), ('ENTREGADO', 'Entregado')], default='INGRESADO', max_length=25),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('notes', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.workorder')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
