# Generated by Django 6.0.5 on 2026-05-15 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_cloudinary_photos_receipts'),
    ]

    operations = [
        migrations.AddField(
            model_name='sparepart',
            name='client_pays',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='workorder',
            name='client_labor_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
