# Generated by Django 6.0.5 on 2026-05-21 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_was_repaired'),
    ]

    operations = [
        migrations.CreateModel(
            name='BonusTier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threshold', models.DecimalField(decimal_places=2, max_digits=12)),
                ('bonus_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('label', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['threshold'],
            },
        ),
    ]
