export const CATEGORY_LABELS_SHORT = {
  HERRAMIENTA_ELECTRICA_CABLE:      'H. eléctrica con cable',
  HERRAMIENTA_ELECTRICA_INALAMBRIC: 'H. eléctrica inalámbrica',
  HERRAMIENTA_NEUMATICA:            'H. neumática',
  HERRAMIENTA_HIDRAULICA:           'H. hidráulica',
  MOTOR_ELECTRICO:                  'Motor eléctrico',
  MOTOR_GASOLINA:                   'Motor gasolina',
  MOTOR_DIESEL:                     'Motor diésel',
  PLANTA_ELECTRICA_GASOLINA:        'Planta gasolina',
  PLANTA_ELECTRICA_DIESEL:          'Planta diésel',
  SOLDADOR_INVERSOR:                'Soldador inversor',
  SOLDADOR_CONVENCIONAL:            'Soldador convencional',
  MOTOSOLDADOR:                     'Motosoldador',
  CORTADOR_PLASMA:                  'Cortador plasma',
  OXICORTE:                         'Oxicorte',
  AGROFORESTAL:                     'Agroforestal',
  LINEA_BLANCA:                     'Línea blanca',
}

export const CATEGORY_LABELS = {
  HERRAMIENTA_ELECTRICA_CABLE:      'Herramienta eléctrica con cable',
  HERRAMIENTA_ELECTRICA_INALAMBRIC: 'Herramienta eléctrica inalámbrica',
  HERRAMIENTA_NEUMATICA:            'Herramienta neumática',
  HERRAMIENTA_HIDRAULICA:           'Herramienta hidráulica',
  MOTOR_ELECTRICO:                  'Motor eléctrico',
  MOTOR_GASOLINA:                   'Motor a gasolina',
  MOTOR_DIESEL:                     'Motor diésel',
  PLANTA_ELECTRICA_GASOLINA:        'Planta eléctrica gasolina',
  PLANTA_ELECTRICA_DIESEL:          'Planta eléctrica diésel',
  SOLDADOR_INVERSOR:                'Soldador inversor',
  SOLDADOR_CONVENCIONAL:            'Soldador convencional',
  MOTOSOLDADOR:                     'Motosoldador',
  CORTADOR_PLASMA:                  'Cortador de plasma',
  OXICORTE:                         'Equipo de oxicorte',
  AGROFORESTAL:                     'Agroforestal',
  LINEA_BLANCA:                     'Línea blanca',
}
